#!/usr/bin/perl

use warnings;
use strict;

use autodie;

my $dir = "$ENV{HOME}/.ssh";

my $key = "$dir/id_rsa";
my $pub_key = "${key}.pub";

die("$0 should have no more then one argument.\n")
   if @ARGV > 1;


my $type = $ARGV[0] // 'default';
my $nkey;
my $pub_nkey;

foreach my $k ("${key}-${type}", "${key}_${type}", "${key}${type}") {
   my $pk = "${k}.pub";
   if (-e $k && -e $pk) {
      $nkey    = $k;
      $pub_nkey = $pk;
   }
}

die("Can't find $nkey and $pub_nkey\n")
   unless ($nkey && $pub_nkey);


if (-l $key && -l $pub_key ) {
   unlink $key, $pub_key;

   symlink $nkey,     $key;
   print "id_rsa --> $nkey\n";
   symlink $pub_nkey, $pub_key;
   print "id_rsa.pub --> $pub_nkey\n";
} else {
   die "$key and $pub_key are not symlinks.\n"
}

